### ISSUE TITLE
Docker image for olaper

### ISSUE THREAD

**Issue by ivansabik** [Wondersoft/olaper#2]
Just jumped into this project, would be nice to have at least a quick and dirty development docker image. Will try to do one once I retake my explorations but if anyone has got one would be nice to share!

**Comment by ivansabik** [comment]
Here's an approach for setting up quickly the foodmart demo for Olaper:

https://github.com/ivansabik/docker-olaper

**Comment by astudnev** [comment]
Thank you, Ivan

i added a link on docker image in doc
